import { Applicant, Job, MenuItem } from "./types/types";

export const navItems: MenuItem[] = [
  {
    title: "Posted Jobs",
    url: "/dashboard/posted-jobs",
    icon: "user",
    shortcut: ["e", "e"],
    isActive: false,
    items: [], // No child items
  },
  {
    title: "Applied Jobs",
    url: "/dashboard/applied-jobs",
    icon: "user",
    shortcut: ["e", "e"],
    isActive: false,
    items: [], // No child items
  },
];

export const jobs: Job[] = [
  {
    id: "1",
    title: "Software Engineer",
    type: "Full-Time",
    location: "New York, NY",
    department: "Engineering",
    employment: "Permanent",
  },
  {
    id: "2",
    title: "Product Manager",
    type: "Full-Time",
    location: "San Francisco, CA",
    department: "Product",
    employment: "Permanent",
  },
  {
    id: "3",
    title: "Data Analyst",
    type: "Part-Time",
    location: "Remote",
    department: "Analytics",
    employment: "Contract",
  },
  {
    id: "4",
    title: "HR Specialist",
    type: "Full-Time",
    location: "Chicago, IL",
    department: "Human Resources",
    employment: "Permanent",
  },
  {
    id: "5",
    title: "Marketing Coordinator",
    type: "Part-Time",
    location: "Remote",
    department: "Marketing",
    employment: "Temporary",
  },
  {
    id: "6",
    title: "Frontend Developer",
    type: "Full-Time",
    location: "Austin, TX",
    department: "Engineering",
    employment: "Permanent",
  },
  {
    id: "7",
    title: "Backend Developer",
    type: "Full-Time",
    location: "Seattle, WA",
    department: "Engineering",
    employment: "Permanent",
  },
  {
    id: "8",
    title: "UI/UX Designer",
    type: "Part-Time",
    location: "Remote",
    department: "Design",
    employment: "Contract",
  },
  {
    id: "9",
    title: "Cybersecurity Analyst",
    type: "Full-Time",
    location: "Washington, D.C.",
    department: "IT",
    employment: "Permanent",
  },
  {
    id: "10",
    title: "Sales Representative",
    type: "Full-Time",
    location: "Dallas, TX",
    department: "Sales",
    employment: "Permanent",
  },
  {
    id: "11",
    title: "Content Writer",
    type: "Part-Time",
    location: "Remote",
    department: "Marketing",
    employment: "Contract",
  },
  {
    id: "12",
    title: "DevOps Engineer",
    type: "Full-Time",
    location: "Boston, MA",
    department: "Engineering",
    employment: "Permanent",
  },
  {
    id: "13",
    title: "Financial Analyst",
    type: "Full-Time",
    location: "Atlanta, GA",
    department: "Finance",
    employment: "Permanent",
  },
  {
    id: "14",
    title: "Quality Assurance Tester",
    type: "Part-Time",
    location: "Remote",
    department: "Engineering",
    employment: "Temporary",
  },
  {
    id: "15",
    title: "IT Support Specialist",
    type: "Full-Time",
    location: "Phoenix, AZ",
    department: "IT",
    employment: "Permanent",
  },
  {
    id: "16",
    title: "Operations Manager",
    type: "Full-Time",
    location: "Los Angeles, CA",
    department: "Operations",
    employment: "Permanent",
  },
  {
    id: "17",
    title: "Graphic Designer",
    type: "Part-Time",
    location: "Remote",
    department: "Design",
    employment: "Contract",
  },
  {
    id: "18",
    title: "Customer Success Manager",
    type: "Full-Time",
    location: "Denver, CO",
    department: "Customer Success",
    employment: "Permanent",
  },
  {
    id: "19",
    title: "Recruiter",
    type: "Part-Time",
    location: "Miami, FL",
    department: "Human Resources",
    employment: "Contract",
  },
  {
    id: "20",
    title: "AI Researcher",
    type: "Full-Time",
    location: "Palo Alto, CA",
    department: "Research",
    employment: "Permanent",
  },
];

export const applicants: Applicant[] = [
  {
    name: "John Doe",
    email: "johndoe@example.com",
    phone: "+1234567890",
    city: "New York",
    experience: "5 years",
    department: "Engineering",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/johndoe_cv.pdf",
  },
  {
    name: "Jane Smith",
    email: "janesmith@example.com",
    phone: "+1987654321",
    city: "San Francisco",
    experience: "3 years",
    department: "Marketing",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/janesmith_cv.pdf",
  },
  {
    name: "Michael Brown",
    email: "michaelbrown@example.com",
    phone: "+1123456789",
    city: "Los Angeles",
    experience: "7 years",
    department: "Finance",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/michaelbrown_cv.pdf",
  },
  {
    name: "Emily Davis",
    email: "emilydavis@example.com",
    phone: "+1212345678",
    city: "Chicago",
    experience: "2 years",
    department: "Human Resources",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/emilydavis_cv.pdf",
  },
  {
    name: "Robert Wilson",
    email: "robertwilson@example.com",
    phone: "+1239876543",
    city: "Houston",
    experience: "6 years",
    department: "Operations",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/robertwilson_cv.pdf",
  },
  {
    name: "Sophia Johnson",
    email: "sophiajohnson@example.com",
    phone: "+1987123456",
    city: "Seattle",
    experience: "4 years",
    department: "Design",
    cv: "https://res.cloudinary.com/demo/image/upload/v1234567890/sophiajohnson_cv.pdf",
  },
];
