export interface Applicant {
  _id?: string; // Optional, as it will be generated by the database
  name: string;
  email: string;
  phone: string;
  city: string;
  experience: string;
  department: string;
  resume: string;
  status?: boolean; // Optional, with default false
  createdAt?: string; // Optional, handled by Mongoose timestamps
  updatedAt?: string; // Optional, handled by Mongoose timestamps
}
